version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    container_name: Users-Info
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresDB: