services:
  postgres:
    image: postgres:latest
    container_name: Users-Info
    environment:
      POSTGRES_USER: farheen
      POSTGRES_PASSWORD: farheen
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farheen -d users"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    platform: linux/amd64
    build: .
    container_name: task2-backend
    environment:
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USERNAME: farheen
      DB_PASSWORD: farheen
      DB_DATABASE: users
    ports:
      - "50000:50000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./src/user-data:/usr/src/app/src/user-data
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: